export const pageOptions = [
  {
    id: 1,
    selected: false,
    pageName: "PercievedThreatMenu",
    title: "Elevated State",
  },
  { id: 2, selected: false, pageName: "Report", title: "My Past Week" },
  { id: 3, selected: false, pageName: "Routine", title: "My Routine" },
  {
    id: 4,
    selected: false,
    pageName: "CopingStatement",
    title: "My Coping Statement",
  },
  { id: 5, selected: false, pageName: "MyValues", title: "My Values" },
  { id: 6, selected: true, pageName: "CheckIn", title: "Quick Check-In" },
  { id: 7, selected: false, pageName: "SelfTalk", title: "+ Self-Talk" },
  { id: 8, selected: false, pageName: "Pies", title: "PIES Check-In" },
  {
    id: 9,
    selected: false,
    pageName: "FocusStatement",
    title: "My Focus Statement",
  },
  { id: 10, selected: false, pageName: "NotesMenu", title: "Experiences" },
  {
    id: 11,
    selected: false,
    pageName: "SoberContacts",
    title: "Support Contacts",
  },
  { id: 12, selected: false, pageName: "ProCon", title: "Pros & Cons" },
  { id: 13, selected: false, pageName: "Activities", title: "Activities" },
  { id: 14, selected: false, pageName: "Five", title: "5-4-3-2-1" },
];
