export const pageOptions = [
  {
    id: 1,
    selected: false,
    pageName: "PercievedThreatMenu",
    sub: "I need to calm down now",
    title: "Elevated State",
  },
  {
    id: 2,
    selected: true,
    pageName: "CheckIn",
    sub: "It takes 30 seconds.",
    title: "Quick Check-In",
  },
  {
    id: 3,
    selected: false,
    pageName: "Routine",
    sub: "The tools that help me most.",
    title: "My Routine",
  },
  {
    id: 4,
    selected: false,
    pageName: "Report",
    sub: "Review your flags and check-ins.",
    title: "My Past Week",
  },
  {
    id: 9,
    selected: false,
    pageName: "FocusStatement",
    sub: "This is who I strive to be.",
    title: "My Focus Statement",
  },
  {
    id: 5,
    selected: false,
    pageName: "CopingStatement",
    sub: "A quick statement for right here and now.",
    title: "My Coping Statement",
  },
  {
    id: 6,
    selected: false,
    pageName: "MyValues",
    sub: "What I hold dear and why I'm doing this.",
    title: "My Values",
  },
  {
    id: 10,
    selected: false,
    pageName: "NotesMenu",
    sub: "The good and the bad.",
    title: "Experiences",
  },
  {
    id: 7,
    selected: false,
    pageName: "SelfTalk",
    sub: "Challenging negativity.",
    title: "+ Self-Talk",
  },
  {
    id: 8,
    selected: false,
    pageName: "Pies",
    sub: "Physical, Insights, Emotions, Spiritually",
    title: "PIES Check-In",
  },
  {
    id: 11,
    selected: false,
    pageName: "SupportContacts",
    sub: "Call the people who will be there for you.",
    title: "Support Contacts",
  },
  {
    id: 12,
    selected: false,
    pageName: "ProCon",
    sub: "Let's weigh it out.",
    title: "Pros & Cons",
  },
  {
    id: 13,
    selected: false,
    pageName: "Activities",
    sub: "I'm bored, let's check some stuff off.",
    title: "Activities",
  },
  {
    id: 14,
    selected: false,
    pageName: "Five",
    sub: "A grounding excersize",
    title: "5-4-3-2-1",
  },
  {
    id: 15,
    selected: false,
    pageName: "Scream",
    title: "Scream",
    sub: "Just let it out.",
  },
  {
    id: 16,
    selected: false,
    pageName: "PMRInstruct",
    sub: "Calm from the head down.",
    title: "Progressive Muscle Relaxation",
  },
  {
    id: 17,
    selected: false,
    pageName: "EyeInstruct",
    title: "Left & Right",
    sub: "Lateral Eye Movements",
  },
  {
    id: 18,
    selected: false,
    pageName: "KneadInstruct",
    title: "Knead your feet",
    sub: "A grounding exercize.",
  },
  {
    id: 19,
    selected: false,
    pageName: "AnkleInstruct",
    title: "Rock the ankles",
    sub: "A an exercize for when standing in line.",
  },
];

export const elevatedOptions = [
  {
    id: 1,
    pageName: "Breathe",
    sub: "A guided breathing exercize.",
    title: "Breathe",
  },
  {
    id: 2,
    pageName: "PMRInstruct",
    sub: "Calm from the head down.",
    title: "Progressive Muscle Relaxation",
  },
  {
    id: 3,
    pageName: "EyeInstruct",
    title: "Left & Right",
    sub: "Lateral Eye Movements",
  },
  {
    id: 4,
    pageName: "KneadInstruct",
    title: "Knead your feet",
    sub: "A grounding exercize.",
  },
  {
    id: 5,
    pageName: "AnkleInstruct",
    title: "Rock the ankles",
    sub: "A an exercize for when standing in line.",
  },
  {
    id: 6,
    pageName: "Scream",
    title: "Scream",
    sub: "Just let it out.",
  },
];